apc.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc.c -o apc.lo 
php_apc.lo: /opt/bms/custom/templates/upload/APC-3.0.14/php_apc.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/php_apc.c -o php_apc.lo 
apc_cache.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_cache.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_cache.c -o apc_cache.lo 
apc_compile.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_compile.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_compile.c -o apc_compile.lo 
apc_debug.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_debug.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_debug.c -o apc_debug.lo 
apc_fcntl.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_fcntl.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_fcntl.c -o apc_fcntl.lo 
apc_main.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_main.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_main.c -o apc_main.lo 
apc_mmap.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_mmap.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_mmap.c -o apc_mmap.lo 
apc_sem.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_sem.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_sem.c -o apc_sem.lo 
apc_shm.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_shm.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_shm.c -o apc_shm.lo 
apc_futex.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_futex.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_futex.c -o apc_futex.lo 
apc_pthreadmutex.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_pthreadmutex.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_pthreadmutex.c -o apc_pthreadmutex.lo 
apc_spin.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_spin.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_spin.c -o apc_spin.lo 
pgsql_s_lock.lo: /opt/bms/custom/templates/upload/APC-3.0.14/pgsql_s_lock.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/pgsql_s_lock.c -o pgsql_s_lock.lo 
apc_sma.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_sma.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_sma.c -o apc_sma.lo 
apc_stack.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_stack.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_stack.c -o apc_stack.lo 
apc_zend.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_zend.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_zend.c -o apc_zend.lo 
apc_rfc1867.lo: /opt/bms/custom/templates/upload/APC-3.0.14/apc_rfc1867.c
	$(LIBTOOL) --mode=compile $(CC) $(APC_CFLAGS) -I. -I/opt/bms/custom/templates/upload/APC-3.0.14 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /opt/bms/custom/templates/upload/APC-3.0.14/apc_rfc1867.c -o apc_rfc1867.lo 
$(phplibdir)/apc.la: ./apc.la
	$(LIBTOOL) --mode=install cp ./apc.la $(phplibdir)

./apc.la: $(shared_objects_apc) $(APC_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_apc) $(APC_SHARED_LIBADD)

